VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

''**************************************************************
'' UserForm1•\Ž¦ƒ{ƒ^ƒ“
''**************************************************************
Private Sub CommandButton1_Click()
    UserForm1.Show
End Sub
